---
- hosts: jenkins-server
  gather_facts: no

  tasks:
  - name: Remove Java 7 and Install Java 8
    block:
    - name: Remove Java7
      yum: name=java7 state=removed
    - name: Install Java 8
      yum: name=java-1.8.0-openjdk-devel.x86_64 state=installed
    become: yes
  
  - name: Install git
    yum: name=git state=installed
    become: yes
  
  - name: Install ansible and boto and boto3
    command: pip install ansible boto boto3
    become: yes
 
  - name: install docker
    yum: name=docker state=installed
    become: yes

  - name: Create /apps directory
    file:
      state: directory
      path: /apps
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
    become: yes
  
  - name: Install and Run Jenkins
    block:
    - name: get jenkins repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: import repo key 
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    - name: install jenkins
      yum: name=jenkins state=installed
    - name: add jenkins to group
      command: usermod -a -G docker jenkins
    - name : source bash profiles
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
    - name: run docker
      service:
        name: docker
        state: started
    - name: start service jenkins
      service:
        name: jenkins
        state: started
    - pause: seconds=20
    - name: read the password file
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: password
    - debug:
        msg:
        - "Jenkins Administrator password: {{password.stdout_lines | replace('[u','') | replace(']','')}}"
        - "Jenkins URL: {{ansible_host}}:8080"
    become: yes

  - name: Copy ssh to jenkins
    copy:
      src: "{{ssh_key}}"
      dest: ~/.ssh/id_rsa
      mode: 0400



# node environment config: PATH: